server:
  port: 9010

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/yo_local
    username: yo
    password: codeclick1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    cors:
      enabled: true

app:
  jwt:
    secret: AjoG+21NgY3GTOhy1NDUR1xmWDrUW+S8q2rTnC3Ko8CkoTpUmOh0xoxxOslUxfV4ntoxnAxpuIR8lvvNpahyEA==
    expiration-sec: 3600000

logging:
  level:
    com.yo.sm: DEBUG
    org.hibernate.SQL: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
